WORLD_STUDIO_HTML = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>OpenRA AI — Earth Mission Studio</title>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<style>
:root{color-scheme:dark;--bg:#0b0d0b;--panel:#141814;--line:#303a30;--text:#eef2e8;--muted:#9aa596;--orange:#ff7048;--gold:#e8c459}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 system-ui,sans-serif}main{display:grid;grid-template-columns:380px 1fr;min-height:100vh}.controls{padding:28px;border-right:1px solid var(--line);background:var(--panel);overflow:auto}.map-wrap{position:relative}#map{position:absolute;inset:0;background:#111}h1{font-size:30px;letter-spacing:-.04em;margin:6px 0}.eyebrow{color:var(--orange);font:700 11px ui-monospace,monospace;letter-spacing:.14em;text-transform:uppercase}p{color:var(--muted)}label{display:block;margin:13px 0 5px;color:#bbc4b6;font:700 10px ui-monospace,monospace;letter-spacing:.09em;text-transform:uppercase}input,select,textarea{width:100%;border:1px solid var(--line);border-radius:7px;background:#0c0f0c;color:var(--text);padding:10px}textarea{height:74px;resize:vertical}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.search{display:flex;gap:7px;margin:18px 0}.search input{flex:1}.search button{white-space:nowrap}button,a.button{border:1px solid #495548;border-radius:7px;background:#20261f;color:var(--text);padding:10px 13px;font-weight:750;cursor:pointer;text-decoration:none;display:inline-flex;justify-content:center;align-items:center}button:hover,a.button:hover{border-color:var(--orange)}button.primary{width:100%;margin-top:18px;background:var(--orange);border-color:var(--orange);color:#1a0b07}.result{margin-top:16px;border:1px solid var(--line);border-radius:8px;padding:13px;background:#0c0f0c;white-space:pre-wrap;font:12px/1.5 ui-monospace,monospace}.actions{display:flex;gap:8px;margin-top:10px}.actions>*{flex:1}.crosshair{position:absolute;z-index:500;left:50%;top:50%;transform:translate(-50%,-50%);pointer-events:none;color:var(--orange);font-size:26px;text-shadow:0 0 8px #000}.leaflet-control-attribution{background:#111b!important;color:#bbb!important}@media(max-width:800px){main{grid-template-columns:1fr}.controls{border-right:0}.map-wrap{min-height:55vh}#map{position:absolute}}
</style></head><body><main><section class="controls"><div class="eyebrow">OpenRA AI / Earth-to-Mission</div><h1>Mission Studio</h1><p>Search or click anywhere on Earth. Roads, water and landform context become a playable Red Alert skirmish.</p>
<div class="search"><input id="query" placeholder="Search city or landmark"><button id="search">Find</button></div>
<div class="row"><div><label>Latitude</label><input id="latitude" type="number" step="any" value="24.7136"></div><div><label>Longitude</label><input id="longitude" type="number" step="any" value="46.6753"></div></div>
<label>Mission title</label><input id="title" value="Earth Skirmish">
<div class="row"><div><label>Battlefield radius</label><select id="radius_m"><option value="500" selected>500 m - tactical</option><option value="750">750 m - neighborhood</option><option value="1000">1 km - local</option><option value="2000">2 km - compressed district</option></select></div><div><label>Map size</label><select id="map_size"><option>64</option><option selected>96</option><option>128</option></select></div></div>
<label>Terrain seed</label><input id="seed" type="number" min="0" value="42">
<label>Story / scenario direction</label><textarea id="story_seed" placeholder="A tense fictional operation around the river crossings…"></textarea>
<button class="primary" id="generate">Generate playable .oramap</button><div id="result" class="result">Choose a location to begin.</div>
<div class="actions"><a class="button" id="download" hidden>Download map</a><a class="button" href="http://127.0.0.1:8787/">AI Console</a></div>
<p>Generated maps are installed into your OpenRA user map folder. Return to the game and choose <b>World Tools → Native Map Editor</b>.</p>
</section><section class="map-wrap"><div id="map"></div><div class="crosshair">⌖</div></section></main>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>
const $=id=>document.getElementById(id), result=$('result'), download=$('download');let map;
function setPoint(lat,lon,zoom=12){$('latitude').value=Number(lat).toFixed(6);$('longitude').value=Number(lon).toFixed(6);if(map)map.setView([lat,lon],zoom)}
if(window.L){map=L.map('map',{zoomControl:true}).setView([24.7136,46.6753],11);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap contributors'}).addTo(map);map.on('click',event=>setPoint(event.latlng.lat,event.latlng.lng,map.getZoom()));map.on('moveend',()=>{const c=map.getCenter();$('latitude').value=c.lat.toFixed(6);$('longitude').value=c.lng.toFixed(6)})}else{result.textContent='Map tiles are unavailable. Enter latitude and longitude manually.'}
$('search').onclick=async()=>{const q=$('query').value.trim();if(!q)return;result.textContent='Searching…';try{const r=await fetch('/v1/geocode?query='+encodeURIComponent(q));const data=await r.json();if(!r.ok)throw new Error(data.detail||data.error);setPoint(data.latitude,data.longitude,12);$('title').value=data.name;result.textContent=`Selected ${data.name}\n${data.latitude}, ${data.longitude}`}catch(e){result.textContent='Search failed: '+e.message}};
$('generate').onclick=async()=>{download.hidden=true;result.textContent='Reading geographic features and compiling OpenRA terrain…';const body={latitude:Number($('latitude').value),longitude:Number($('longitude').value),title:$('title').value,radius_m:Number($('radius_m').value),map_size:Number($('map_size').value),seed:Number($('seed').value),story_seed:$('story_seed').value,source:'openstreetmap'};try{const r=await fetch('/v1/missions/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.detail||data.error);result.textContent=`READY\nSource: ${data.source_status}\nValid: ${data.validation.valid}\nInstalled: ${data.filename}`;download.href=data.download_url;download.download=data.filename;download.hidden=false}catch(e){result.textContent='Generation failed: '+e.message}};
</script></body></html>"""
